Repository DeFiCh/salmon, pull requests merged in 2021-06, with the labels that each got.

#18 updated projects health file
  .editorconfig
  .gitignore
  .idea/README.md
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dictionaries/fuxing.xml
  .idea/modules.xml
  .idea/salmon.iml
  CONTRIBUTING.md
  Dockerfile
  LICENSE
  README.md
  package.json
Labels: kind/chore

#19 clean up workflows
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-enhancement.md
  .github/ISSUE_TEMPLATE/3-general.md
  .github/dependabot.yml
  .github/governance.yml
  .github/labeler.yml
  .github/labels.yml
  .github/workflows/ci.yml
  .github/workflows/defichain-dependencies.yml
  .github/workflows/oss-governance-bot.yml
  .github/workflows/oss-governance-labeler.yml
  .github/workflows/oss-governance-project-issue.yml
  .github/workflows/oss-governance-project-pr.yml
  .github/workflows/oss-governance-project.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-publish.yml
  .github/workflows/sync-labels.yml
Labels: area/workflow, kind/chore

#22 added setup with tests
  README.md
  jest.config.js
  package-lock.json
  package.json
  packages/salmon-oracles-functions/__tests__/index.test.ts
  packages/salmon-oracles-functions/__tests__/provider.mock.ts
  packages/salmon-oracles-functions/jest.config.js
  packages/salmon-oracles-functions/package.json
  packages/salmon-oracles-functions/src/index.ts
  packages/salmon-oracles-functions/tsconfig.build.json
  packages/salmon-oracles-functions/tsconfig.json
  tsconfig.base.json
  tsconfig.build.json
  tsconfig.json
Labels: kind/chore

#17 Added initial packages and config files
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  packages/salmon-lambda-functions/jest.config.js
  packages/salmon-lambda-functions/package.json
  packages/salmon-lambda-functions/src/index.ts
  packages/salmon-lambda-functions/tsconfig.json
  packages/salmon-price-functions/__test__/price_manager.test.ts
  packages/salmon-price-functions/jest.config.js
  packages/salmon-price-functions/package.json
  packages/salmon-price-functions/src/index.ts
  packages/salmon-price-functions/tsconfig.build.json
  packages/salmon-price-functions/tsconfig.json
  tsconfig.build.json
  tsconfig.json
Labels: kind/feature

#25 Added tests for config parsing
  packages/salmon-price-functions/README.md
  packages/salmon-price-functions/__test__/config.test.ts
  packages/salmon-price-functions/__test__/fetch_value.test.ts
Labels: kind/chore

#27 added new context holder and peer reviewer for project salmon
  .github/CODEOWNERS
Labels: area/workflow, kind/chore

#32 Cleaned up jest config
  jest.config.js
  packages/salmon-lambda-functions/jest.config.js
  packages/salmon-oracles-functions/jest.config.js
  packages/salmon-price-functions/jest.config.js
Labels: kind/chore

#34 Update oss-governance-labeler.yml
  .github/workflows/oss-governance-labeler.yml
Labels: area/workflow, kind/chore

#37 Update CODEOWNERS
  .github/CODEOWNERS
Labels: area/workflow, kind/chore

#35 Refactored price manager to use provider pattern
  package-lock.json
  package.json
  packages/salmon-price-functions/__test__/config.test.ts
  packages/salmon-price-functions/__test__/fetch_asset_prices.test.ts
  packages/salmon-price-functions/__test__/fetch_asset_prices_multiple.test.ts
  packages/salmon-price-functions/__test__/fetch_value.test.ts
  packages/salmon-price-functions/package.json
  packages/salmon-price-functions/src/index.ts
  packages/salmon-price-functions/src/price_manager.ts
  packages/salmon-price-functions/src/price_provider.ts
  packages/salmon-price-functions/src/providers/finnhubb.ts
  packages/salmon-price-functions/src/providers/iex_cloud.ts
  packages/salmon-price-functions/src/providers/index.ts
  packages/salmon-price-functions/src/providers/tiingo.ts
Labels: kind/feature

#33 Add basic oracles test
  .husky/pre-commit
  packages/salmon-oracles-functions/__tests__/basic_oracle.test.ts
  packages/salmon-oracles-functions/__tests__/index.test.ts
  packages/salmon-oracles-functions/__tests__/test.utils.ts
  packages/salmon-oracles-functions/src/index.ts
Labels: area/module-defid, area/salmon-api-wallet, kind/chore

#40 Added asset filter and malformed data test
  packages/salmon-price-functions/__test__/fetch_asset_prices.test.ts
  packages/salmon-price-functions/__test__/fetch_asset_prices_multiple.test.ts
  packages/salmon-price-functions/__test__/timestamps.test.ts
  packages/salmon-price-functions/src/price_manager.ts
Labels: kind/chore

#38 Tidied up tests, constructor and packages
  package.json
  packages/salmon-price-functions/__test__/fetch_asset_prices.test.ts
  packages/salmon-price-functions/__test__/fetch_asset_prices_multiple.test.ts
  packages/salmon-price-functions/src/price_manager.ts
Labels: kind/chore

#45 Introduce lambda function and package scripts
  package-lock.json
  package.json
  packages/salmon-lambda-functions/package.json
  packages/salmon-lambda-functions/src/index.ts
  packages/salmon-lambda-functions/tsconfig.build.json
  packages/salmon-lambda-functions/tsconfig.json
  packages/salmon-oracles-functions/package.json
  packages/salmon-price-functions/tsconfig.json
  tsconfig.build.json
  tsconfig.json
Labels: kind/feature

#53 improved @defichain/* update workflow
  .github/workflows/defichain-dependencies.yml
  .github/workflows/oss-governance-project-pr.yml
  packages/salmon-lambda-functions/package.json
  packages/salmon-oracles-functions/package.json
  packages/salmon-price-functions/package.json
Labels: area/workflow, kind/chore

#55 ncu will only create PR if there are changes
  .github/workflows/defichain-dependencies.yml
Labels: area/workflow, kind/chore

#52 Integrate Whale Client
  jest.config.js
  packages/salmon-lambda-functions/package.json
  packages/salmon-lambda-functions/src/finnhubb.ts
  packages/salmon-lambda-functions/src/iexcloud.ts
  packages/salmon-lambda-functions/src/tiingo.ts
  packages/salmon-oracles-functions/__tests__/basic_oracle.test.ts
  packages/salmon-oracles-functions/__tests__/whale_client.test.ts
  packages/salmon-oracles-functions/package.json
  packages/salmon-oracles-functions/src/index.ts
  packages/salmon-oracles-functions/src/oraclesManager.ts
  packages/salmon-oracles-functions/src/salmonWalletHDNode.ts
Labels: kind/feature

#58 Added timestamp filter to lambda functions
  packages/salmon-lambda-functions/src/finnhubb.ts
  packages/salmon-lambda-functions/src/generic/index.ts
  packages/salmon-lambda-functions/src/iexcloud.ts
  packages/salmon-lambda-functions/src/tiingo.ts
Labels: kind/feature

#59 Add end to end test
  .github/workflows/ci.yml
  .github/workflows/e2e/docker-compose.yml
  .github/workflows/e2e/mocks_finnhubb.js
  .github/workflows/e2e/mocks_iexcloud.js
  .github/workflows/e2e/mocks_tiingo.js
  .github/workflows/e2e/setup.js
  .github/workflows/e2e/test.finnhubb.test.js
  .github/workflows/e2e/test.iexcloud.test.js
  .github/workflows/e2e/test.tiingo.test.js
  .github/workflows/e2e/test.weighted.test.js
  .github/workflows/e2e/wait-for
  jest.config.e2e.js
  jest.config.js
  package.json
  packages/salmon-lambda-functions/package.json
  packages/salmon-lambda-functions/src/generic/index.ts
  packages/salmon-oracles-functions/__tests__/whale_client_blockchain.test.ts
Labels: area/workflow, kind/feature

#64 Update README.md
  README.md
Labels: needs/kind

#67 Added key retrieval from SSM
  README.md
  package-lock.json
  packages/salmon-lambda-functions/package.json
  packages/salmon-lambda-functions/src/generic/index.ts
  packages/salmon-oracles-functions/__tests__/whale_client.test.ts
  packages/salmon-oracles-functions/package.json
  tsconfig.build.json
  tsconfig.json
Labels: kind/feature
